version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: /VUUc25h_BQZmg5
      POSTGRES_USER: postgres.pwmyzjakquansgufouyw
      POSTGRES_DB: postgres

  app:
    image: my-node-app
    ports: 
      - 8000:8000