version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: MetroDB

  app:
    image: my-node-app
    ports: 
      - 8000:8000
