CREATE DATABASE METRO;

CREATE TABLE USER{
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(50) NOT NULL,
    wallet_balance DECIMAL(10,2) NOT NULL,
}

CREATE TABLE TRAIN{
    train_id INT PRIMARY KEY AUTO_INCREMENT,
    train_name VARCHAR(50) NOT NULL,
    capacity INT NOT NULL,
}

CREATE TABLE STATION{
    STATION_ID INT PRIMARY KEY AUTO_INCREMENT,
    STATION_NAME VARCHAR(50) NOT NULL,
    LATITUDE DECIMAL(11,8) NOT NULL,
    LONGITUDE DECIMAL(11,8) NOT NULL,
}

CREATE TABLE STOP{
    STOP_ID INT PRIMARY KEY AUTO_INCREMENT,
    TRAIN_ID INT NOT NULL,
    STATION_ID INT NOT NULL,
    ARRIVAL_TIME TEXT NOT NULL,
    DEPARTURE_TIME TEXT NOT NULL,
    FARE DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN(ID),
    FOREIGN KEY (STATION_ID) REFERENCES STATION(STATION_ID),
}



CREATE TABLE TICKET{
    TICKET_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    TRAIN_ID INT NOT NULL,
    SOURCE_STATION_ID INT NOT NULL,
    DESTINATION_STATION_ID INT NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN(ID),
    FOREIGN KEY (SOURCE_STATION_ID) REFERENCES STATION(STATION_ID),
    FOREIGN KEY (DESTINATION_STATION_ID) REFERENCES STATION(STATION_ID),
}

