

DROP TABLE IF EXISTS TICKET;
DROP TABLE IF EXISTS STOPAGE;
DROP TABLE IF EXISTS STATION;
DROP TABLE IF EXISTS TRAIN;
DROP TABLE IF EXISTS "USER";
CREATE TABLE "USER" (
    user_id SERIAL PRIMARY KEY,
    user_name VARCHAR(50) NOT NULL,
    wallet_balance DECIMAL(10,2) NOT NULL
);


CREATE TABLE TRAIN (
    train_id SERIAL PRIMARY KEY,
    train_name VARCHAR(50) NOT NULL,
    capacity INT NOT NULL
);


CREATE TABLE STATION (
    STATION_ID SERIAL PRIMARY KEY,
    STATION_NAME VARCHAR(50) NOT NULL,
    LATITUDE DECIMAL(11,8) NOT NULL,
    LONGITUDE DECIMAL(11,8) NOT NULL
);


CREATE TABLE STOPAGE (
    STOP_ID SERIAL PRIMARY KEY,
    TRAIN_ID INT NOT NULL,
    STATION_ID INT NOT NULL,
    ARRIVAL_TIME TEXT NOT NULL,
    DEPARTURE_TIME TEXT NOT NULL,
    FARE DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN(train_id),
    FOREIGN KEY (STATION_ID) REFERENCES STATION(STATION_ID)
);


CREATE TABLE TICKET (
    TICKET_ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    TRAIN_ID INT NOT NULL,
    SOURCE_STATION_ID INT NOT NULL,
    DESTINATION_STATION_ID INT NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES "USER"(user_id),
    FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN(train_id),
    FOREIGN KEY (SOURCE_STATION_ID) REFERENCES STATION(STATION_ID),
    FOREIGN KEY (DESTINATION_STATION_ID) REFERENCES STATION(STATION_ID)
);
